---
- name: Login accounts
  include_tasks: login.yaml
  loop: "{{ harica_api_accounts | dict2items(key_name='type', value_name='details') }}"
  loop_control:
    loop_var: login

- name: Request certificates
  include_tasks: request_cert.yaml
  loop: "{{ harica_api_certificates | dict2items | map(attribute='value') | list }}"
  loop_control:
    loop_var: harica_api_certificate
  ignore_errors: true
